name: Run iOS Unit Tests

on:
  pull_request:
    branches:
      - main  # Or your default branch

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Install Bundler and Gems
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install

      # Optional: Uncomment if you need to enforce a specific Xcode version
      # - name: Select Xcode 16.3
      #   run: sudo xcode-select -s /Applications/Xcode_16.3.app

      - name: Run Unit Tests with Fastlane
        env:
          FASTLANE_DISABLE_USAGE: 'true'
          FASTLANE_OPT_OUT_USAGE: 'true'
          FASTLANE_SKIP_UPDATE_CHECK: 'true'
          FASTLANE_SKIP_DOCS: 'true'
          CI: 'true'
        run: bundle exec fastlane test